#!/usr/bin/python3

import datetime
import shutil
import subprocess

dzisiaj = datetime.datetime.now().strftime("%F")

subprocess.run(["tar", "zcvf", "etc-kopia-python-" + dzisiaj+ ".tar.gz", "/etc"])

shutil.copy("etc-kopia-python-" + dzisiaj+ ".tar.gz", "/tmp/")

